# Generated by Django 4.0.3 on 2022-03-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmdetails',
            name='age_rating',
            field=models.CharField(max_length=10),
        ),
    ]
