# Generated by Django 4.0.4 on 2022-05-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0002_alter_student_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='in_club',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
