# Generated by Django 4.0.3 on 2022-03-24 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0003_delete_screendetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_available', models.PositiveIntegerField()),
                ('name_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='user_page.filmdetails')),
                ('showings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='user_page.showingdetails')),
            ],
            options={
                'db_table': 'Screens',
            },
        ),
    ]
