# Generated by Django 4.0.4 on 2022-05-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0003_student_in_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='in_club',
        ),
    ]
