# Generated by Django 4.0.4 on 2022-05-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0004_remove_student_in_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='in_club',
            field=models.CharField(choices=[('yes', 'Choice1'), ('no', 'Chouce2')], default='no', max_length=5),
        ),
    ]
