# Generated by Django 4.0.3 on 2022-03-24 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0005_remove_screendetails_name_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screendetails',
            name='Films',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_page.filmdetails'),
        ),
        migrations.AddField(
            model_name='screendetails',
            name='Showings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_page.showingdetails'),
        ),
        migrations.AddField(
            model_name='showingdetails',
            name='Films',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_page.filmdetails'),
        ),
    ]
