# Generated by Django 4.0.3 on 2022-03-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0006_screendetails_films_screendetails_showings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showingdetails',
            name='time',
            field=models.TimeField(help_text='Example: 10:30AM'),
        ),
    ]
