# Generated by Django 4.0.4 on 2022-05-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0006_alter_student_in_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='landline_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
