# Generated by Django 4.0.3 on 2022-03-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0008_carddetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardDetails',
        ),
    ]
