# Generated by Django 4.0.3 on 2022-03-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0012_alter_carddetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
