# Generated by Django 4.0.3 on 2022-03-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0013_alter_carddetails_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardDetails',
        ),
    ]
