# Generated by Django 4.0.4 on 2022-05-09 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0013_removestaffdetails_remove_club_representatives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_page.screendetails'),
        ),
    ]
