# Generated by Django 4.0.3 on 2022-03-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0002_alter_filmdetails_age_rating'),
        ('user_page', '0014_delete_carddetails'),
    ]

    operations = [
    ]
