# Generated by Django 4.0.4 on 2022-05-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0014_alter_orderdetails_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_page.screendetails'),
        ),
    ]
