# Generated by Django 4.0.3 on 2022-03-28 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0015_merge_20220329_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Club name')),
                ('address', models.CharField(max_length=50, verbose_name='Address: ')),
                ('address2', models.CharField(blank=True, default='', max_length=50, verbose_name='Address 2 (Optional): ')),
                ('city', models.CharField(default='', max_length=30, verbose_name='City: ')),
                ('postcode', models.CharField(default='', max_length=7, verbose_name='Postcode: ')),
                ('contact_number', models.IntegerField()),
                ('landline_number', models.IntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='showingdetails',
            name='date',
            field=models.DateField(help_text='Example: 2022-01-01'),
        ),
        migrations.AlterField(
            model_name='showingdetails',
            name='time',
            field=models.TimeField(help_text='Example: 10:30'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('Club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_page.club')),
            ],
        ),
        migrations.CreateModel(
            name='Representatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('Club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_page.club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='Representatives',
            field=models.ManyToManyField(blank=True, to='user_page.representatives'),
        ),
        migrations.AddField(
            model_name='club',
            name='Students',
            field=models.ManyToManyField(blank=True, to='user_page.student'),
        ),
    ]
