# Generated by Django 4.0.4 on 2022-05-09 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0016_alter_showingdetails_films'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usename', models.CharField(max_length=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_page.orderdetails')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
    ]
