# Generated by Django 4.0.4 on 2022-05-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0017_paidorderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidorderdetails',
            name='order',
        ),
        migrations.AddField(
            model_name='paidorderdetails',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='paidorderdetails',
            name='price',
            field=models.PositiveBigIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='paidorderdetails',
            name='screen_type',
            field=models.CharField(default='2D', max_length=5),
        ),
        migrations.AddField(
            model_name='paidorderdetails',
            name='selected_seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paidorderdetails',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
