# Generated by Django 4.0.4 on 2022-05-09 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0018_remove_paidorderdetails_order_paidorderdetails_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidorderdetails',
            name='screen_type',
        ),
        migrations.RemoveField(
            model_name='paidorderdetails',
            name='time',
        ),
    ]
