# Generated by Django 4.0.4 on 2022-05-09 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0019_remove_paidorderdetails_screen_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidorderdetails',
            name='selected_seats',
        ),
    ]
