# Generated by Django 4.0.4 on 2022-05-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0020_remove_paidorderdetails_selected_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidorderdetails',
            old_name='usename',
            new_name='username',
        ),
    ]
