# Generated by Django 4.0.4 on 2022-10-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0016_club_alter_showingdetails_date_and_more'),
        ('user_page', '0022_alter_paidorderdetails_price'),
    ]

    operations = [
    ]
